name: 'AWS S3'
description: 'Sync files to S3'
author: 'Richard Willis <willis.rh@gmail.com>'
branding:
  icon: 'upload-cloud'
  color: 'gray-dark'
inputs:
  bucket:
    required: true
    description: 'The name of the S3 bucket'
  action:
    required: true
    description: 'The action to perform. Accepted values: sync|clean'
  srcDir:
    required: false
    default: ''
    description: 'Source directory of local files to sync (if using the sync action)'
  filesGlob:
    required: false
    default: ''
    description: 'Glob pattern for source files to sync to S3 (if using the sync action)'
  awsRegion:
    require: true
    description: 'The AWS region. For example: us-east-1'
  prefix:
    require: false
    default: ''
    description: "The prefix for the uploaded object. For example: 'custom/folder'"
  stripExtensionGlob:
    require: false
    default: ''
    description: "Glob pattern to strip extension (f using the sync action). For example: '**/**.html'"
  cacheControl:
    require: false
    default: ''
    description: 'Cache-control headers. For example: public,max-age=31536000,immutable'
  acl:
    required: false
    default: ''
    description: '"authenticated-read" | "aws-exec-read" | "bucket-owner-full-control" | "bucket-owner-read" | "private" | "public-read" | "public-read-write"'
outputs:
  S3SyncedFiles:
    description: 'A comma separated list of objects keys for files synced to S3. For example: file1,folder1/file2'
runs:
  using: 'node16'
  main: 'dist/index.js'
