name: 'AWS S3 Actions'
description: 'Perform actions on a S3 bucket like sync or clean files. Includes accurate ETAG comparisons and parallel uploads with configurable concurrency & multipart chunk sizes.'
author: 'Richard Willis <willis.rh@gmail.com>'
branding:
  icon: 'upload-cloud'
  color: 'gray-dark'
inputs:
  bucket:
    required: true
    description: 'The name of the S3 bucket'
  action:
    required: true
    description: 'The action to perform. Accepted values: sync|clean'
  src-dir:
    required: false
    default: ''
    description: 'Source directory of local files to sync (if using the sync action)'
  files-glob:
    required: false
    default: ''
    description: 'Glob pattern for source files to sync to S3 (if using the sync action)'
  aws-region:
    require: true
    description: 'The AWS region. For example: us-east-1'
  prefix:
    require: false
    default: ''
    description: "The prefix for the uploaded object. For example: 'custom/folder'"
  strip-extension-glob:
    require: false
    default: ''
    description: "Glob pattern to strip extension (f using the sync action). For example: '**/**.html'"
  cache-control:
    require: false
    default: ''
    description: 'Cache-control headers. For example: public,max-age=31536000,immutable'
  acl:
    required: false
    default: ''
    description: '"authenticated-read" | "aws-exec-read" | "bucket-owner-full-control" | "bucket-owner-read" | "private" | "public-read" | "public-read-write"'
  multipart-file-size-mb:
    required: false
    default: 100
    description: 'The minimum file size, in megabytes, for which to upload files using multipart. The default is 100'
  multipart-chunk-bytes:
    required: false
    default: 10485760
    description: 'The chunk size, in bytes, to upload multipart file parts in. The default is 10485760 (10MB)'
  concurrency:
    required: false
    default: 6
    description: 'How many processes to perform at once. Default is 6'
outputs:
  modified-keys:
    description: 'A comma separated list of modified object keys (either synced or removed). For example: file1,folder1/file2.ext'
runs:
  using: 'node16'
  main: 'dist/index.js'
