name: 'Sync S3'

concurrency:
  group: prod_deploy
  cancel-in-progress: false

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'Sync'
    runs-on: ubuntu-20.04
    if: github.actor != 'dependabot[bot]' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: badsyntax/github-action-aws-cloudformation@v0.0.5
        name: Update CloudFormation Stack
        id: update-stack
        with:
          stack-name: 'badsyntax-github-action-example-aws-s3'
          template: './cloudformation/s3bucket-example.yml'
          apply-change-set: ${{ github.event_name != 'repository_dispatch' }}
          aws-region: 'us-east-1'
          parameters: 'S3BucketName=badsyntax-github-action-example-aws-s3-us-east-1&S3AllowedOrigins=https://richardwillis.info'

      - uses: ./
        name: Sync HTML files to S3
        id: sync-html-s3
        with:
          bucket: ${{ steps.update-stack.outputs.S3BucketName }}
          action: 'sync'
          src-dir: './out'
          files-glob: '**/*.html'
          aws-region: 'us-east-1'
          prefix: 'preview'
          strip-extension-glob: '**/**.html'
          cache-control: 'public,max-age=0,s-maxage=31536000,must-revalidate'

      - uses: ./
        name: Sync immutable files to S3
        id: sync-immutable-s3
        with:
          bucket: ${{ steps.update-stack.outputs.S3BucketName }}
          action: 'sync'
          src-dir: './out'
          files-glob: 'css/**'
          aws-region: 'us-east-1'
          prefix: 'preview'
          cache-control: 'public,max-age=31536000,immutable'

      - name: Output Synced Files
        run: |
          echo "Synced HTML Files: $S3SyncedHTMLFiles"
          echo "Synced Immutable Files: $S3SyncedImmutableFiles"
        env:
          # Use outputs from the S3 step
          S3SyncedHTMLFiles: ${{ steps.sync-html-s3.outputs.modified-keys }}
          S3SyncedImmutableFiles: ${{ steps.sync-immutable-s3.outputs.modified-keys }}
